language: ruby

rvm:
  - 2.2.4

sudo: false
cache: bundler
pre_script:
  - bundle exec rake generate_blade_yml

script:
 - bundle exec rake test
 - bundle exec blade ci

gemfile:
  - Gemfile.rails50
  - Gemfile.rails42
