language: ruby

rvm:
  - 2.0.0
  - 2.1.7
  - 2.2.3

sudo: false
cache: bundler

script:
 - bundle exec rake test
 - bundle exec blade ci

gemfile:
  - Gemfile.rails50

matrix:
  exclude:
    - gemfile: Gemfile.rails50
      rvm: 2.0.0
    - gemfile: Gemfile.rails50
      rvm: 2.1.7
