
matrix:
  include:
    - language: ruby
      rvm: 2.5
      gemfile: props_template/Gemfile.rails60
      before_install:
        - cd props_template
      install:
        - bundle install
      script:
        - bundle exec rspec

    - language: ruby
      rvm: 2.5
      env:
        - NODE_VERSION="10.13.0"
      gemfile: breezy_rails/Gemfile.rails60
      addons:
        chrome: stable
      before_install:
        - wget -N http://chromedriver.storage.googleapis.com/80.0.3987.16/chromedriver_linux64.zip -P ~/
        - unzip ~/chromedriver_linux64.zip -d ~/
        - rm ~/chromedriver_linux64.zip
        - sudo mv -f ~/chromedriver /usr/local/share/
        - sudo chmod +x /usr/local/share/chromedriver
        - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
        - nvm install $NODE_VERSION
        - node --version
        - cd breezy_rails
      install:
        - bundle install
      script:
        - bundle exec rake test
        - BUNDLE_GEMFILE='' ruby -Ilib:test test/acceptance/breezy_installation_acceptance.rb

    - language: node_js
      node_js: 8
      before_install:
        - cd breezy
      install:
        - npm install
      script:
        - npm run lint
        - npm run test
