matrix:
  include:
    - language: ruby
      rvm: 2.3
      gemfile: breezy_template/Gemfile.rails42
      before_install:
        - cd breezy_template
      install:
        - bundle install
      script:
        - bundle exec rake test
    - language: ruby
      rvm: 2.3
      gemfile: breezy_template/Gemfile.rails50
      before_install:
        - cd breezy_template
      install:
        - bundle install
      script:
        - bundle exec rake test
    - language: node_js
      node_js: 8
      before_install:
        - cd breezy
      install:
        - npm install
      script:
        - npm run lint
        - npm run test
