# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 35115cee4b11f2b83d018aa0872f1b1e8f69d424b61050e04d436997c2d6a73b8a45fb2fdaf9589879d6682d86a5dbdcf7fc073728c45fbe1b4251e68cf4e3df

test:
  secret_key_base: 1a0c66b1d0eca596762f0d2430d5947ea3570f37d791c872d8c959d16165f7266391d5539c468dcf7fb29f38e3c75b6da4f197a6da448aef3643eafe7645b437

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
